export const CAR_MAKES_MODELS: Record<string, string[]> = {
  'Audi': ['A1','A2','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q7','Q8','TT','R8','e-tron','S3','S4','S5','RS3','RS4','RS5','RS6','RS7'],
  'BMW': ['1 Series','2 Series','3 Series','4 Series','5 Series','6 Series','7 Series','8 Series','X1','X2','X3','X4','X5','X6','X7','Z4','M2','M3','M4','M5','M8','iX','i4','i7'],
  'Mercedes-Benz': ['A-Class','B-Class','C-Class','CLA','CLS','E-Class','EQA','EQB','EQC','EQE','EQS','G-Class','GLA','GLB','GLC','GLE','GLS','S-Class','SL','AMG GT','V-Class','Vito'],
  'Volkswagen': ['Polo','Polo Vivo','Golf','Golf GTI','Golf R','Passat','Tiguan','Touareg','T-Roc','T-Cross','Amarok','Transporter','Caddy','Scirocco','Up'],
  'Toyota': ['Agya','Aygo','Corolla','Corolla Cross','Camry','Hilux','Fortuner','RAV4','Land Cruiser','Land Cruiser Prado','Prius','Starlet','Avanza','Innova','Hiace','Quantum','Yaris'],
  'Ford': ['Fiesta','Focus','Mustang','Ranger','Everest','Puma','EcoSport','Kuga','Explorer','Maverick','Transit','Transit Custom','Galaxy','S-Max','Tourneo'],
  'Hyundai': ['i10','i20','i30','Elantra','Sonata','Tucson','Santa Fe','Kona','Venue','Staria','H-1','Creta','Grand i10'],
  'Kia': ['Picanto','Rio','Cerato','Stinger','Sportage','Sorento','Telluride','Carnival','EV6','Sonet','Seltos','Niro'],
  'Nissan': ['Micra','Almera','Sentra','Tiida','Altima','Maxima','Juke','Qashqai','X-Trail','Patrol','Navara','NP200','NP300','Leaf'],
  'Honda': ['Jazz','Ballade','Civic','Accord','CR-V','HR-V','Pilot','Ridgeline','Fit','City','WR-V'],
  'Mazda': ['Mazda2','Mazda3','Mazda6','CX-3','CX-30','CX-5','CX-8','MX-5','BT-50'],
  'Mitsubishi': ['Mirage','Attrage','Lancer','Eclipse Cross','ASX','Outlander','Pajero','Pajero Sport','Triton','Express'],
  'Subaru': ['Impreza','Legacy','Outback','Forester','XV','WRX','WRX STI','BRZ','Crosstrek'],
  'Suzuki': ['Alto','Celerio','Swift','Baleno','Ignis','Jimny','Vitara','S-Cross','Ertiga','Grand Vitara','Dzire'],
  'Chevrolet': ['Spark','Sonic','Cruze','Malibu','Captiva','Trax','Trailblazer','Colorado','Silverado','Camaro','Corvette'],
  'Renault': ['Kwid','Sandero','Logan','Clio','Megane','Talisman','Duster','Kadjar','Koleos','Captur','Triber','Kiger','Master','Trafic'],
  'Peugeot': ['108','208','308','508','2008','3008','5008','Partner','Expert','Boxer'],
  'Citroën': ['C1','C3','C3 Aircross','C4','C4 Cactus','C5 Aircross','Berlingo','SpaceTourer'],
  'Fiat': ['500','Panda','Punto','Tipo','500X','500L','Doblo','Ducato'],
  'Jeep': ['Renegade','Compass','Cherokee','Grand Cherokee','Gladiator','Wrangler','Commander'],
  'Land Rover': ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
  'Volvo': ['S60','S90','V60','V90','XC40','XC60','XC90','C40'],
  'Lexus': ['CT','IS','ES','GS','LS','UX','NX','RX','GX','LX','LC','RC'],
  'Infiniti': ['Q30','Q50','Q60','Q70','QX30','QX50','QX60','QX70','QX80'],
  'Porsche': ['911','718 Boxster','718 Cayman','Panamera','Macan','Cayenne','Taycan'],
  'Isuzu': ['KB','D-Max','MU-X','NPR','NQR','NMR','FVR'],
  'Mahindra': ['KUV100','XUV300','XUV500','XUV700','Bolero','Scorpio','TUV300','Thar','Pik Up'],
  'GWM': ['P-Series','Steed','Cannon','Ute','Haval H1','Haval H2','Haval H6','Haval Jolion','Haval H9','ORA'],
  'BAIC': ['X25','X35','X55','BJ40','BJ80','D20','A-Series'],
  'Chery': ['QQ','Tiggo 4','Tiggo 7','Tiggo 7 Pro','Tiggo 8','Tiggo 8 Pro'],
  'Opel': ['Adam','Corsa','Astra','Insignia','Mokka','Crossland','Grandland','Zafira','Vivaro'],
  'Alfa Romeo': ['MiTo','Giulia','Stelvio','Tonale','Giulietta','4C'],
  'Jaguar': ['E-Pace','F-Pace','F-Type','I-Pace','XE','XF','XJ'],
  'Maserati': ['Ghibli','Quattroporte','Levante','GranTurismo','GranCabrio','Grecale'],
  'Bentley': ['Bentayga','Continental GT','Flying Spur','Mulsanne'],
  'Rolls-Royce': ['Ghost','Phantom','Wraith','Dawn','Cullinan','Spectre'],
  'Lamborghini': ['Huracan','Urus','Revuelto'],
  'Ferrari': ['Roma','Portofino','SF90','F8','296','812'],
  'McLaren': ['Artura','GT','720S','765LT'],
  'Other': ['Other'],
}

export const MOTORBIKE_MAKES_MODELS: Record<string, string[]> = {
  'Honda': ['CB125R','CB300R','CB500F','CB500X','CB650R','CB750 Hornet','CB1000R','CBR300R','CBR500R','CBR650R','CBR1000RR','CRF300L','CRF300 Rally','CRF1100L Africa Twin','NC750X','NT1100','X-ADV','PCX125','PCX160','ADV350','Forza 350','Forza 750','Gold Wing','Rebel 500','Rebel 1100'],
  'Yamaha': ['YZF-R3','YZF-R7','YZF-R1','MT-03','MT-07','MT-09','MT-10','Tracer 7','Tracer 9','Ténéré 700','FZ1','FZ6','XSR700','XSR900','TMAX 560','NMAX 155','Aerox 155','Xmax 300'],
  'Kawasaki': ['Ninja 400','Ninja 650','Ninja ZX-4R','Ninja ZX-6R','Ninja ZX-10R','Ninja H2','Z400','Z650','Z900','Z1000','Versys 650','Versys 1000','KLR650','KLX300','W800','Vulcan S','Eliminator'],
  'Suzuki': ['GSX-S750','GSX-S950','GSX-S1000','GSX-R600','GSX-R750','GSX-R1000','V-Strom 650','V-Strom 1050','SV650','Boulevard M109R','Burgman 400','GSX250R'],
  'KTM': ['125 Duke','200 Duke','390 Duke','490 Duke','790 Duke','890 Duke','1290 Super Duke','390 Adventure','790 Adventure','890 Adventure','1090 Adventure','1190 Adventure','1290 Super Adventure','RC 390','RC 8C'],
  'BMW Motorrad': ['G 310 R','G 310 GS','F 750 GS','F 850 GS','F 900 R','F 900 XR','F 900 GS','R nineT','R nineT Scrambler','R nineT Pure','R nineT Racer','R nineT Urban GS','R 1250 GS','R 1250 GS Adventure','R 1250 RT','R 1250 R','R 1250 RS','R 90','R 90 S','R 80','R 75','S 1000 R','S 1000 RR','S 1000 XR','M 1000 RR','M 1000 R','K 1600 GT','K 1600 GTL','K 1600 Grand America','CE 04','CE 02'],
  'Ducati': ['Monster 937','Monster SP','Streetfighter V2','Streetfighter V4','Panigale V2','Panigale V4','Multistrada V2','Multistrada V4','Hypermotard 950','Desert Sled','Scrambler Icon','Scrambler Full Throttle','XDiavel','Diavel V4','SuperSport 950'],
  'Triumph': ['Street Triple','Speed Triple','Daytona 660','Trident 660','Tiger 660','Tiger 900','Tiger 1200','Bonneville T100','Bonneville T120','Scrambler 400','Scrambler 900','Scrambler 1200','Speed Twin','Rocket 3','Thunderbird'],
  'Royal Enfield': ['Hunter 350','Meteor 350','Classic 350','Classic 500','Bullet 350','Himalayan','Scram 411','Interceptor 650','Continental GT 650','Super Meteor 650'],
  'Harley-Davidson': ['Street 500','Iron 883','Forty-Eight','SuperLow','Street Glide','Road Glide','Road King','Fat Boy','Softail Standard','Breakout','Pan America 1250','Nightster','Sportster S','Low Rider'],
  'Aprilia': ['RS 457','RS 660','RSV4','Tuono 660','Tuono V4','Dorsoduro 900','Shiver 900','Caponord 1200','SX 125','RX 125'],
  'MV Agusta': ['Brutale 800','Brutale 1000','F3 800','F4','Turismo Veloce','Superveloce'],
  'Benelli': ['302R','502C','752S','BN 302','TRK 502','TRK 702','Leoncino 500','TNT 600'],
  'CFMoto': ['300NK','450NK','650NK','700CL-X','800MT','1000NK'],
  'Zontes': ['ZT125-U','ZT250-GK','ZT350-T','ZT350-R','ZT500-R'],
  'Other': ['Other'],
}

export const CAR_MAKES = Object.keys(CAR_MAKES_MODELS).sort()
export const MOTORBIKE_MAKES = Object.keys(MOTORBIKE_MAKES_MODELS).sort()

// ─── Vehicle Colours ──────────────────────────────────────────

export const VEHICLE_COLOURS = [
  'Alpine White', 'Pearl White', 'Solid White',
  'Metallic Silver', 'Mineral Silver', 'Titanium Silver',
  'Mineral Grey', 'Graphite Grey', 'Space Grey', 'Jet Black',
  'Carbon Black', 'Midnight Black', 'Sapphire Black',
  'Estoril Blue', 'Portimao Blue', 'Misano Blue', 'Deep Sea Blue',
  'Melbourne Red', 'Imola Red', 'Chilli Red', 'San Marino Red',
  'Java Green', 'British Racing Green',
  'Sunset Orange', 'Fire Orange',
  'Sunset Yellow', 'Austin Yellow',
  'Frozen Brown', 'Champagne Gold',
  'Other',
]
